### ISSUE TITLE
Question - does it work with motion sensors

### ISSUE THREAD

**Issue by molinto** [FruitieX/lightctl-koa#1]
Hi, I'm looking for a way to send Hue Motion sensors to IFTTT. Wonder if yours can send data to a 3rd party API like IFTTT.

Thanks
Sharry

**Comment by FruitieX** [comment]
Sorry for super late reply, I'm getting too much spam on GitHub and issues may slip by in my inbox. :(

In the unlikely event you didn't resolve this yet, then yes, you could use lightctl's sensor polling ability and easily forward events to another service such as IFTTT.

**Comment by FruitieX** [comment]
Please re-open if you're still interested in this :)
